// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgrepo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TelemetryDatum struct {
	DeviceID   string
	Timestamp  pgtype.Timestamp
	StateName  string
	StateValue []byte
}
